name: "CD Pipeline"

on:
  workflow_run:
    workflows: ["Sample React CI Pipeline / Workflow"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: "Clone the repository"
        uses: actions/checkout@v4

      - name: "Setup nodejs"
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: "Setup vercel cli"
        run: npm install -g vercel

      - name: "Download build files"
        uses: actions/download-artifact@v4
        with:
          name: build
          run-id: ${{ github.event.workflow_run.id || github.run_id }}
          github-token: ${{ github.token }}
          path: dist

      # CHANGES ARE IN THIS STEP BELOW
      - name: "Deploy to vercel"
        run: |
          # 1. Pull down Vercel configurations and create a local build-ready link
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

          # 2. Tell Vercel to build locally (this registers your 'dist' folder)
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

          # 3. Deploy the precompiled local build instantly
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
